#file: noinspection SpringBootApplicationYaml
spring:
  application:
    name : "object-storage"
  minio:
    endpoint: http://192.168.19.19:9000
    accessKey: admin
    secretKey: admin123
    bucketName: my-bucket
